name: Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Get current time
      id: time
      run: echo "::set-output name=time::$(date +'%Y-%m-%d %H:%M:%S %Z')"

    - name: Send custom message
      uses: appleboy/telegram-action@v0.1.0
      with:
        to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          The ${{ github.event_name }} event triggered the final step.
          This event is a ${{ github.event_name }} by ${{ github.actor }}.
          Time: ${{ steps.time.outputs.time }}
